version: '2'
services:
  mysql:
    image: mariadb:10.2
    volumes:
      - mysql-vol-1:/var/lib/mysql
      - ./docker/conf/mysql/:/etc/mysql/conf.d/:ro
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    restart: always
    networks:
      app-network:
        aliases:
          - mysql
  php-fpm:
    image: feldsam/phpfpm:0.1
    build: ./docker/dockerfiles/phpfpm
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - mysql
    volumes:
      - ./app:/web:rw
      - ./docker/conf/phpfpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - TZ=${TZ}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
    restart: always
    networks:
      app-network:
        aliases:
          - phpfpm
          
  memcached:
    image: memcached:alpine
    restart: always
    networks:
      app-network:
        aliases:
          - memcached
          
  nginx:
    depends_on:
      - php-fpm
    image: nginx:mainline-alpine
    volumes:
      - ./app:/web:ro
      - ./docker/conf/nginx/:/etc/nginx/conf.d/:ro
    ports:
      - "${HTTP_BIND}:${HTTP_PORT}:80"
    restart: always
    networks:
      app-network:
        aliases:
          - nginx
          
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24

volumes:
  mysql-vol-1: